config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'users#new'

	 resource :user
	 resources :vehicles do
		 resources :reservations
     resources :availabilities
	 end
	 resource :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	#owner
	has_many :owned_vehicles, class_name: 'Vehicle', foreign_key: :owner_id
	has_many :vehicle_reservations, class_name: 'Reservation', source: :reservations, through: :owned_vehicles, foreign_key: :owner_id
  has_many :availabilities, through: :owned_vehicles, foreign_key: :owner_id
  #passenger
	has_many :trips, class_name: 'Reservation', foreign_key: :passenger_id
	has_many :rented_vehicles, class_name: 'Vehicle', source: :vehicle, through: :trips

	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, on: :create
	validates :password_confirmation, presence: true, on: :create
	validates :first_name, :last_name, :phone_number, :email, :date_of_birth, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
    render :new, layout: 'homepage'
  end

  def create
    @user = User.new(user_params)
    @user.date_of_birth = Date.new(params[:date][:year].to_i, params[:date][:month].to_i,params[:date][:day].to_i).in_time_zone('Eastern Time (US & Canada)')
    if @user.save
      session[:user_id] = @user.id
      redirect_back fallback_location: vehicles_url
    else
      # flash[:notice] = "Invalid Email or Password"
      # redirect_to new_users_url
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update

    @user = current_user
    if @user.update_attributes(user_params)
       @user.date_of_birth = Date.new(params[:date][:year].to_i, params[:date][:month].to_i,params[:date][:day].to_i)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :root
  end

  private
  def user_params()
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :date_of_birth, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_signup-login-form.html.erb
<!-- <div class="">
  <h2 class=''></h2> <h2 class=''></h2>
</div> -->

<div class="edit-user-container">

  <%= form_for current_user do |f| %>
    <%if current_user.errors.any? %>
      <div class="error_messages">
        <h2>Entry is invalid</h2>
        <ul>
          <% current_user.errors.full_messages.each do |message| %>
            <li> <%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <!-- <div class="">
    <h2>Account Info</h2>
    <div class="">
      <%#= f.label :password %>
      <%#= f.password_field :password %>
    </div>
    <div class="">
      <%#= f.label :password_confirmation %>
      <%#= f.password_field :password_confirmation %>
    </div>
  </div> -->

  <div class="edit-user-form">

      <div class="user-attr">
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>

      <div class="user-attr">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>

      <div class="user-attr">
        <%= f.label :phone_number %>
        <%= f.telephone_field :phone_number %>
      </div>

      <div class="user-attr">
        <%= f.label :date_of_birth %>
        <%= select_year(Date.today, start_year: 1920, end_year: 1998) %>
        <%= select_month DateTime.now %>
        <%= select_day DateTime.now  %>
      </div>

      <div class="signup-button edit-button">
        <%= f.submit 'Submit', class: "signup-button" %>
      </div>

  </div>
<% end %>
</div>

<!-- <div class="">

  <h1>Login</h1>

  <button type="button" class="close-button">x</button>
  <%= form_tag sessions_path do%>
  <div class="">
    <%= label_tag :email %><%= text_field_tag :email, params[:email] %>
  </div>
  <div class="">
    <%= label_tag :password %><%= password_field_tag :password %>
  </div>
  <div class="login-button">
    <%= submit_tag "Login", class: "login-button" %>
  </div>
</div>
<% end %> -->

<!-- <div class="homepage-search">
	<%= form_tag vehicles_path, method: :get, class: "navbar-form navbar-left search-form" do %>
	  <%= text_field_tag(
	      :search,
	      params[:search],
	      placeholder: "Where would you like to go?",
	      class: "homepage-form-control"
	  ) %>
		 <%= submit_tag "Search", class: "btn-btn-primary" %>
	<% end %>

  <% if @vehicles.present? %>
    <% render :vehicles %>
  <% end %>
</div> -->

app/views/users/edit.html.erb
<div class="user-edit-container">

  <h2 class="edit-user-h2"> Edit Info </h1>

  <%= render "signup-login-form" %>
</div>

app/views/users/new.html.erb
<div class="main-page-slogan slogan-top">
  <h1 id='slogan'>The car is yours for the ride.</h1>
</div>

<div class="homepage-login-container">
  <div class="homepage">

    <div class="homepage-search search-top">
      <%= form_tag vehicles_path, method: :get, class: "navbar-form navbar-left search-form" do %>
        <%= text_field_tag(
            :search,
            params[:search],
            placeholder: "Where would you like to go?",
            class: "homepage-form-control"
        ) %>
         <%= submit_tag "Search", class: "btn-btn-primary" %>
      <% end %>

      <% if @vehicles.present? %>
        <% render :vehicles %>
      <% end %>
    </div>


    <div class="login-signup-btns">
      <% unless current_user %>
        <h2 class='login-btn'>Login</h2> <h2 class='signup-btn'>Signup</h2>
      <% end %>
    </div>

    <div class="signup-container">

      <h1>Sign Up</h1>

      <%= form_for(@user, url: user_path) do |f| %>
        <%if @user.errors.any? %>
          <div class="error_messages">
            <h2>Entry is invalid</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li> <%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="account-info">
          <h2>Account Info</h2>

          <button type="button" class="close-button">x</button>

          <div class="form-line">
            <%= f.label :email %>
            <%= f.email_field :email %>
          </div>

          <div class="form-line">
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>

          <div class="form-line">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
          </div>
        </div>


        <div class="personal-info">

          <h2>Personal Information</h2>

          <div class="form-line">
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
          </div>

          <div class="form-line">
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
          </div>

          <div class="form-line">
            <%= f.label :phone_number %>
            <%= f.telephone_field :phone_number %>
          </div>

          <div class="form-line">
            <%= f.label :date_of_birth %>
            <%= select_year(Date.today, start_year: 1920, end_year: 1998) %>
            <%= select_month DateTime.now %>
            <%= select_day DateTime.now  %>
          </div>

          <div class="signup-button">
            <%= f.submit 'Submit', class: "signup-button" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="login-container">

      <h1>Login</h1>

      <button type="button" class="close-button">x</button>
      <%= form_tag sessions_path do%>
        <div class="form-line">
          <%= label_tag :email %><%= text_field_tag :email, params[:email] %>
        </div>
        <div class="form-line">
          <%= label_tag :password %><%= password_field_tag :password %>
        </div>
        <div class="login-button">
          <%= submit_tag "Login", class: "login-button" %>
        </div>
      <% end %>
    </div>
  </div>

</div>

<div class="homepage-search search-bottom">
  <%= form_tag vehicles_path, method: :get, class: "navbar-form navbar-left search-form" do %>
    <%= text_field_tag(
        :search,
        params[:search],
        placeholder: "Where would you like to go?",
        class: "homepage-form-control"
    ) %>
     <%= submit_tag "Search", class: "btn-btn-primary" %>
  <% end %>

  <% if @vehicles.present? %>
    <% render :vehicles %>
  <% end %>
</div>

<div class="main-page-slogan slogan-bottom">
  <h1 id='slogan'>The car is yours for the ride.</h1>
</div>

<div id="about-container">

  <h1 id='about'>About</h1>
  <div class="about-content">
    <p>Car sharing for the New Age.</p>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>

  <div class="about-image">
    <img src="https://s-media-cache-ak0.pinimg.com/originals/27/33/16/27331688760948ec9adfcd99ba62bf59.jpg" alt="">
  </div>

</div>

<div id="contact-container">
  <h1 id ='contact'>Contact</h1>
  <div class="contact-content">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>

</div>

<script type="text/javascript">
  if ($("#search").val() != "") {
    $('html,body').animate({
      scrollTop: $("#avail-header").offset().top
    });
  }
</script>

app/views/users/show.html.erb
<div class="profile-container">
  <div class="profile-page">

  <% if current_user %>

    <div class="profile-details">

      <section class="user-info">
        <h2 class="user-info-h2">Personal Info</h2>
        <h3 class="user-info-h3"><span>Name</span> <%= current_user.first_name %> <%= current_user.last_name %></h3>
        <h3 class="user-info-h3"><span>Phone Number</span> <%= current_user.phone_number %></h3>
        <h3 class="user-info-h3"><span>Email</span> <%= current_user.email %></h3>
        <h3 class="user-info-h3"><span>Birthdate</span> <%= current_user.date_of_birth.strftime("%A %B %d, %Y") %></h3>

        <p id="edit-user-link"><%= link_to 'Edit Profile', edit_user_path %></p>
      </section>

      <% if current_user.owned_vehicles.any? do |vehicle| %>
        <section class="reservation-vehicle-show">
          <h2 class="user-info-h2">Your Vehicle</h2>
          <li><h3 class="vehicle-info-h3"><%= vehicle.vehicle_year %> <%= vehicle.vehicle_make %> <%= vehicle.vehicle_model %></h3></li>
          <p id="show-vehicle-link"><%= link_to 'Vehicle Page', vehicle_path(vehicle) %></p>
          <p id="edit-vehicle-link"><%= link_to 'Edit Vehicle', edit_vehicle_path(vehicle) %></p>
          <div class="availability-link-button">
            <p id="availability-link"><%= link_to 'Availability', vehicle_availabilities_path(vehicle) %></p>
          </div>
          <% end %>
        </section>
      <% end %>
    </div>

    <% current_user.trips.each do |trip| %>
      <div class="user-reservations-container">
        <section class="reservation-profile">
          <h2 id="profile-heading">Reservations</h2>
          <h3 class="user-info-h3"><span>Date:</span> <%= trip.start_time.strftime("%A %B %d, %Y") %></h3><h3 class="user-info-h3"><span>Time:</span> <%= trip.start_time.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %p") %></h3>
          <h3 class="user-info-h3"><span>From:</span> <%= trip.start_location %></h3>
          <h3 class="user-info-h3"><span>To:</span> <%= trip.destination %></h3>
          <h3 class="user-info-h3"><span>Number of Passengers:</span> <%= trip.seats %></h3>
          <p id="edit-reservation-link"><%= link_to 'Edit Reservation', edit_vehicle_reservation_path(trip.vehicle_id, trip) %></p>
          <p id="view-reservation-link"><%= link_to 'View Reservation', vehicle_reservation_path(trip.vehicle_id, trip) %></p>
        </section>
      </div>
    <% end %>
  <% end %>

  </div>
</div>