config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'users#new'

	 resource :user
	 resources :vehicles do
		 resources :reservations
     resources :availabilities
	 end
	 resource :sessions, only: [:new, :create, :destroy]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	has_one :owner, class_name: 'User', through: :vehicle
	belongs_to :vehicle
	belongs_to :passenger, class_name: 'User'

	validates_presence_of :start_time, :end_time, :start_location, :destination, :seats
  validate :not_past_date, :capacity, :not_booked, :available_check

  def not_past_date
    if self.start_time < DateTime.now
      errors.add(:start_time, "Time and Date can't be in the past")
    end
  end

  def capacity
    if seats
      if self.vehicle.seats > 0 && self.vehicle.seats >= seats
        return true
      else
        errors.add(:seats, "Number of passengers for this vehicle must be between 1 and #{self.vehicle.seats}")
        return false
      end
    end
  end

  def not_booked
    self.vehicle.reservations.each do |booked|
      if booked.start_time <= self.end_time && self.start_time <= booked.end_time
        errors.add(:start_time, "Vehicle not available at this time")
        return false
      else
        return true
      end
    end
  end

  def available_check
    if available? == false
      errors.add(:start_time, "Vehicle not available at this time")
    end
  end

  def available?
    self.vehicle.availabilities.each do |availability|
      if self.start_time.strftime("%A") == availability.weekday && self.start_time.strftime("%A") == self.end_time.strftime("%A")
        # checking reservation weekday is same as availability weekday && reservation is on same day
        if self.start_time.strftime("%k%M").to_i < availability.start_time || self.end_time.strftime("%k%M").to_i > availability.end_time
          #checking reservation start is earlier than availability start && reservation end is later than availability end
          return false
        end
      end
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
before_action :load_vehicle
before_action :current_user

	def index
		@reservations = Reservation.all
	end

	def new
		@reservation = Reservation.new
		@vehicle = Vehicle.find(params[:vehicle_id])
		@user = User.new
	end

	def show
		@reservation = Reservation.find(params[:id])
		@vehicle = Vehicle.find(params[:vehicle_id])
	end

	def edit
		@reservation = Reservation.find(params[:id])
	end

	def create
		@reservation = Reservation.new(reservation_params)
    @reservation.start_time = DateTime.new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i, params[:date][:hour].to_i, params[:date][:minute].to_i).in_time_zone('Eastern Time (US & Canada)')
    @reservation.end_time = @reservation.start_time + 1.hour
    @reservation.vehicle = Vehicle.find(params[:vehicle_id])
		@reservation.passenger = current_user

    if @reservation.save
			redirect_to vehicle_reservation_url(@vehicle, @reservation)
		else
			render :new
		end
	end

	def update
		@reservation = Reservation.find(params[:id])
    @reservation.start_time = DateTime.new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i, params[:date][:hour].to_i, params[:date][:minute].to_i).in_time_zone('Eastern Time (US & Canada)')
    @reservation.end_time = @reservation.start_time + 1.hour
    @reservation.vehicle = Vehicle.find(params[:vehicle_id])

		if @reservation.update_attributes(reservation_params)
			redirect_to vehicle_reservation_url(@vehicle, @reservation)
		else
			render :edit
		end
	end

	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.destroy
		redirect_to '/user'
	end

	private
	def reservation_params
		params.require(:reservation).permit(:start_time, :end_time, :start_location, :destination, :comment, :vehicle_id, :passenger_id, :seats)
	end

	def load_vehicle
		@vehicle = Vehicle.find(params[:vehicle_id])
	end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<% if @reservation.errors.any? %>
  <div>
    <h2><%= pluralize(@reservation.errors.count, "error") %></h2>

    <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="reserve-form">
<%= form_for [@vehicle, @reservation] do |f| %>
<% f.hidden_field :vehicle_id, value: @vehicle.id %>

  <div class="reserve-form-input">
    <%= f.label "Date" %><br>
    <%= select_month DateTime.now %>
    <%= select_day DateTime.now  %>
    <%= select_year DateTime.now %>
  </div>

  <div class="reserve-form-input">
    <%= f.label "Start Time" %><br>
    <%= select_hour DateTime.now %>
    <%= select_minute DateTime.now  %>
  </div>

  <div class="reserve-form-input">
    <%= f.label "Start Location:" %><br>
    <%= f.text_field :start_location %>
  </div>

  <div class="reserve-form-input">
    <%= f.label "Destination:" %><br>
    <%= f.text_field :destination %>
  </div>

  <div class="reserve-form-input">
    <%= f.label "Number of Passengers:" %><br>
    <%= f.number_field :seats %>
  </div>

  <div class="reserv-btn">
    <%= submit_tag "Submit", class:"reserve-btn-text"%> <%= link_to "Back", user_url(@user), class: "reserve-back-btn" %>
  </div>



<% end %>
</div>

app/views/reservations/edit.html.erb
<div class="edit-reservation-container">

  <h2 class="edit-reservation-h2">Edit Reservation</h2>

  <%= render 'form' %>

</div>

app/views/reservations/index.html.erb
<h1><%= @vehicle.owner.first_name %>'s Vehicle's Reservations</h1>

<% if current_user == @vehicle.owner %>
  <% @vehicle.reservations.each do |reservation| %>
    <p>Date: <%= reservation.start_time.strftime("%A %B %d, %Y") %></p>
    <p>Start Time: <%= reservation.start_time.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %p") %></p>
    <p>Start Location: <%= reservation.start_location %></p>
  	<p>Destination: <%= reservation.destination %></p>
    <p>Number of Passengers: <%= reservation.seats %></p>
    <% end %>
<% else %>
  <p>Sorry, only owner's have access to their vehicle's reservations</p>
<% end %>

app/views/reservations/new.html.erb
<!-- <%= link_to "Back to Reservation", new_vehicle_reservation_url%>
 -->
<% if current_user %>
<div class="reserve">
  <div class="reserve-container">
    <h1 id='reserv-header'>When do you need a ride?</h1>

        <%= render 'form' %>
      
  </div>

</div>

<% else %>

<div class="reserve">


  <div class="reserve-con">

    <p id='signin-alert-reserv'> Please Signup or Login to make a reservation</p>

  <div class="usersignup-container">

  <div class="login-reserv login-reserv-lg">

    <h1 id='login-signup-header'>Login</h1>
    <%= form_tag sessions_path do%>
    <div class="reserv-label">
      <%= label_tag :email %><%= text_field_tag :email, params[:email] %>
    </div>
    <div class="reserv-label">
      <%= label_tag :password %><%= password_field_tag :password %>
    </div>
    <div class="login-button-reserv">
      <%= submit_tag "Submit", class: "login-btn-text" %>
    </div>
  <%end%>
  </div>

  <div class="signup-reserv">

    <h1 id='login-signup-header'>Sign Up</h1>

    <%= form_for(@user, url: user_path) do |f| %>
      <%if @user.errors.any? %>
        <div class="error_messages">
          <h2>Entry is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li> <%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="">

        <div class="reserv-label">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>

        <div class="reserv-label">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>

        <div class="reserv-label">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
      </div>


      <div class="">

          <div class="reserv-label">
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
          </div>

          <div class="reserv-label">
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
          </div>

          <div class="reserv-label">
            <%= f.label :phone_number %>
            <%= f.telephone_field :phone_number %>
          </div>

          <div class="reserv-label">
            <%= f.label :date_of_birth %><br>
            <%= select_year(Date.today, start_year: 1920, end_year: 1998) %>
            <%= select_month DateTime.now %>
            <%= select_day DateTime.now  %>
          </div>

          <div class="signup-button-reserv">
            <%= f.submit 'Submit', class: "signup-btn-text" %>
          </div>

      </div>
    <% end %>
    </div>
  </div>
 </div>
  </div>


</div>

<% end %>

app/views/reservations/show.html.erb
<div class="reserve" id="reserve-show-page">
  <div class="reserve_show_container">
    <div class="reserve-container" id="reserve-show-container">
      <h2>Your Reservation</h2>

      <p>Date: <%= @reservation.start_time.strftime("%A %B %d, %Y") %></p>
      <p>Start Time: <%= @reservation.start_time.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %p") %></p>
      <p>Start Location: <span id="start-address"><%= @reservation.start_location %></span></p>
      <p>Destination: <span id="end-address"><%= @reservation.destination %></span></p>
      <p>Number of Passengers: <%= @reservation.seats %></p>

      <div class="res-btn">
      <span id="res-link"> <%= link_to "Edit Reservation", edit_vehicle_reservation_path(@vehicle, @reservation) %> </span>
      <span id="res-link"> <%= link_to "Delete", vehicle_reservation_path(@vehicle, @reservation), method: :delete %> </span>
      <span id="res-link">  <%= link_to "Back", user_url(@user) %> </span>
      </div>
    </div>
    <div id="res-map"></div>
  </div>
</div>



<script>
  function initMap() {
    var directionsDisplay = new google.maps.DirectionsRenderer;
    var directionsService = new google.maps.DirectionsService;
    var map = new google.maps.Map(document.getElementById('res-map'), {
      zoom: 7,
      scrollwheel: false,
      styles: [
        {elementType: 'geometry', stylers: [{color: '#242f3e'}]},
        {elementType: 'labels.text.stroke', stylers: [{color: '#242f3e'}]},
        {elementType: 'labels.text.fill', stylers: [{color: '#746855'}]},
        {
          featureType: 'administrative.locality',
          elementType: 'labels.text.fill',
          stylers: [{color: '#d59563'}]
        },
        {
          featureType: 'poi',
          elementType: 'labels.text.fill',
          stylers: [{color: '#d59563'}]
        },
        {
          featureType: 'poi.park',
          elementType: 'geometry',
          stylers: [{color: '#263c3f'}]
        },
        {
          featureType: 'poi.park',
          elementType: 'labels.text.fill',
          stylers: [{color: '#6b9a76'}]
        },
        {
          featureType: 'road',
          elementType: 'geometry',
          stylers: [{color: '#38414e'}]
        },
        {
          featureType: 'road',
          elementType: 'geometry.stroke',
          stylers: [{color: '#212a37'}]
        },
        {
          featureType: 'road',
          elementType: 'labels.text.fill',
          stylers: [{color: '#9ca5b3'}]
        },
        {
          featureType: 'road.highway',
          elementType: 'geometry',
          stylers: [{color: '#746855'}]
        },
        {
          featureType: 'road.highway',
          elementType: 'geometry.stroke',
          stylers: [{color: '#1f2835'}]
        },
        {
          featureType: 'road.highway',
          elementType: 'labels.text.fill',
          stylers: [{color: '#f3d19c'}]
        },
        {
          featureType: 'transit',
          elementType: 'geometry',
          stylers: [{color: '#2f3948'}]
        },
        {
          featureType: 'transit.station',
          elementType: 'labels.text.fill',
          stylers: [{color: '#d59563'}]
        },
        {
          featureType: 'water',
          elementType: 'geometry',
          stylers: [{color: '#17263c'}]
        },
        {
          featureType: 'water',
          elementType: 'labels.text.fill',
          stylers: [{color: '#515c6d'}]
        },
        {
          featureType: 'water',
          elementType: 'labels.text.stroke',
          stylers: [{color: '#17263c'}]
        }
      ]
    });
    directionsDisplay.setMap(map);
    calculateAndDisplayRoute(directionsService, directionsDisplay);
  }

  function calculateAndDisplayRoute(directionsService, directionsDisplay) {
    var start = document.getElementById('start-address').innerHTML;
    var end = document.getElementById('end-address').innerHTML;
    directionsService.route({
      origin: start,
      destination: end,
      travelMode: 'DRIVING'
    }, function(response, status) {
      if (status === 'OK') {
        directionsDisplay.setDirections(response);
      } else {
        window.alert('Directions request failed due to ' + status);
      }
    });
  }
</script>

<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-Sq6ZBy9oC33y1vxqvw6p42Yw-UUfwws&callback=initMap">
</script>