config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'users#new'

	 resource :user
	 resources :vehicles do
		 resources :reservations
     resources :availabilities
	 end
	 resource :sessions, only: [:new, :create, :destroy]
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	has_many :reservations
  has_many :availabilities
	has_many :passengers, class_name: 'User', through: :reservations
	belongs_to :owner, class_name: 'User'

	validates_presence_of :vehicle_year, :vehicle_make, :vehicle_model, :street_address, :city, :province, :postal_code, :seats

	def self.search(search)

	  where("city ILIKE ?", "%#{search}%")
		.or(where("vehicle_make ILIKE ?", "%#{search}%"))
		.or(where("vehicle_model ILIKE ?", "%#{search}%"))
		.or(where("province ILIKE ?", "%#{search}%"))
		# .or(where("seats >= ?", "#{search.to_i}"))

	end



end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
	before_action :current_user, only: [:create, :update, :destroy]

	def index
		@vehicles = Vehicle.all
		#if search render results else render vehicles.all
		if params[:search]
			@vehicles = Vehicle.search(params[:search])
		else
			@vehicles = Vehicle.all
		end


	end

	def new
		@vehicle = Vehicle.new
	end

	def create
		@vehicle = Vehicle.new(vehicle_params)
		@vehicle.owner_id = current_user.id

		if @vehicle.save
      Availability.create(start_time: 0, end_time: 0, weekday: 'Monday', vehicle_id: @vehicle.id)
      Availability.create(start_time: 0, end_time: 0, weekday: 'Tuesday', vehicle_id: @vehicle.id)
      Availability.create(start_time: 0, end_time: 0, weekday: 'Wednesday', vehicle_id: @vehicle.id)
      Availability.create(start_time: 0, end_time: 0, weekday: 'Thursday', vehicle_id: @vehicle.id)
      Availability.create(start_time: 0, end_time: 0, weekday: 'Friday', vehicle_id: @vehicle.id)
      Availability.create(start_time: 0, end_time: 0, weekday: 'Saturday', vehicle_id: @vehicle.id)
      Availability.create(start_time: 0, end_time: 0, weekday: 'Sunday', vehicle_id: @vehicle.id)
			redirect_to vehicle_url(@vehicle)
		else
			render :new
		end
	end

	def show
		@vehicle = Vehicle.find(params[:id])
	end

	def edit
		@vehicle = Vehicle.find(params[:id])
	end

	def update
		@vehicle = Vehicle.find(params[:id])

		if @vehicle.update_attributes(vehicle_params)
			redirect_to vehicle_url(@vehicle)
		else
			render :edit
		end
	end

	def destroy
		@vehicle = Vehicle.find(params[:id])
		@vehicle.destroy
		redirect_to '/user'
	end

	private

	def vehicle_params
		params.require(:vehicle).permit(:vehicle_year, :vehicle_make, :vehicle_model, :street_address, :city, :province, :postal_code, :seats, :owner_id, :image)
	end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for @vehicle do |f| %>
	<% if @vehicle.errors.any? %>
		<div class="error_messages">
			<ul>
				<% @vehicle.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
  <div class="vehicle_form">
  	<div class="vehicle-form-input">
  		<% f.hidden_field :owner_id, value: @owner_id %>
  	</div>
  	<div class="vehicle-form-input">
  		<%= f.label :vehicle_year %><br>
  		<%= f.number_field :vehicle_year %>
  	</div>
  	<div class="vehicle-form-input">
  		<%= f.label :vehicle_make %><br>
  		<%= f.text_field :vehicle_make %>
  	</div>
  	<div class="vehicle-form-input">
  		<%= f.label :vehicle_model %><br>
  		<%= f.text_field :vehicle_model %>
  	</div>
  	<div class="vehicle-form-input">
  		<%= f.label :seats %><br>
  		<%= f.number_field :seats %>
  	</div>
  	<div class="vehicle-form-input" id="vehicle_street_address">
  		<%= f.label :street_address %><br>
  		<%= f.text_field :street_address %>
  	</div>
  	<div class="vehicle-form-input" id="vehicle_city">
  		<%= f.label :city %><br>
  		<%= f.text_field :city %>
  	</div>
  	<div class="vehicle-form-input" id="vehicle_province">
  		<%= f.label :province %><br>
  		<%= f.text_field :province %>
  	</div>
  	<div class="vehicle-form-input" id="vehicle_postal_code">
  		<%= f.label :postal_code %><br>
  		<%= f.text_field :postal_code %>
  	</div>
  	<div class="new-vehicle-button"><%= submit_tag "Submit", class: 'new-veh-btn-text' %></div>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Edit Your Vehicle</h1>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<div class="search-background">


	<div class="search-header">


		<div class="vehicle-search">
			<h1 id='slogan2'>Enjoy a carefree ride. </h1>
			<%= form_tag vehicles_path, method: :get, class: "search-bar" do %>
				<%= text_field_tag(
						:search,
						params[:search],
						placeholder: "Where would you like to travel?",
						class: "form-control search-bar",


				) %>
				 <%= submit_tag "Search", class: "btn btn-primary ttl" %>
			<% end %>
		</div>
  </div>
	<h3 class="map-title">Vehicle Locator</h3>
	<div id="map"></div>

		<script>
			function initMap() {
				var toronto = {lat: 43.7184038, lng: -79.5181441};
				var map = new google.maps.Map(document.getElementById('map'), {
					zoom: 12,
	        scrollwheel: false,
					center: toronto,
          styles: [
            {elementType: 'geometry', stylers: [{color: '#242f3e'}]},
            {elementType: 'labels.text.stroke', stylers: [{color: '#242f3e'}]},
            {elementType: 'labels.text.fill', stylers: [{color: '#746855'}]},
            {
              featureType: 'administrative.locality',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'poi',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'poi.park',
              elementType: 'geometry',
              stylers: [{color: '#263c3f'}]
            },
            {
              featureType: 'poi.park',
              elementType: 'labels.text.fill',
              stylers: [{color: '#6b9a76'}]
            },
            {
              featureType: 'road',
              elementType: 'geometry',
              stylers: [{color: '#38414e'}]
            },
            {
              featureType: 'road',
              elementType: 'geometry.stroke',
              stylers: [{color: '#212a37'}]
            },
            {
              featureType: 'road',
              elementType: 'labels.text.fill',
              stylers: [{color: '#9ca5b3'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'geometry',
              stylers: [{color: '#746855'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'geometry.stroke',
              stylers: [{color: '#1f2835'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'labels.text.fill',
              stylers: [{color: '#f3d19c'}]
            },
            {
              featureType: 'transit',
              elementType: 'geometry',
              stylers: [{color: '#2f3948'}]
            },
            {
              featureType: 'transit.station',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'water',
              elementType: 'geometry',
              stylers: [{color: '#17263c'}]
            },
            {
              featureType: 'water',
              elementType: 'labels.text.fill',
              stylers: [{color: '#515c6d'}]
            },
            {
              featureType: 'water',
              elementType: 'labels.text.stroke',
              stylers: [{color: '#17263c'}]
            }
          ]
				});

				var geocoder = new google.maps.Geocoder();
				var vehicles = [];
				$.each($('.vehicle-address'), function (index, vehicle) {
					vehicles.push(vehicle.innerHTML);
				});

				for (var i = 0; i < vehicles.length; i++) {
					geocoder.geocode({'address': vehicles[i]}, function(results, status) {
						if (status === 'OK') {
							map.setCenter(results[0].geometry.location);
							var marker = new google.maps.Marker({
								map: map,
								position: results[0].geometry.location
								});
						} else {
							alert('Geocode was not successful for the following reason: ' + status);
						}
					});
				}
			}
		</script>

		<div class="vehicle-index">
		<h1 id='avail-header'>Available Vehicles</h1>
		<% if @vehicles.present? %>
		<% else %>
			<p id='no-search-results'>Sorry there are no vehicles available in your area.</p>
		<% end %>
			<% @vehicles.each do |vehicle| %>
				<article class="vehicle-container">
		      <div class="vehicle-text">
		  			<h2><%= vehicle.owner.first_name %>'s - <%= vehicle.vehicle_year %> <%= vehicle.vehicle_make %> <%= vehicle.vehicle_model %></h2>
		  			<h3>Seats: <%= vehicle.seats %></h3>
		  			<h3>Address: <span class="vehicle-address"><%= vehicle.street_address %>, <%= vehicle.city %></span></h3>
		    		<ul ><li class='vehicle-link'><%= link_to 'Vehicle Page', vehicle_path(vehicle) %> </li> <li class='vehicle-link'> <%= link_to 'Reserve Vehicle', new_vehicle_reservation_path(vehicle) %></li></ul>
		      </div>
				</article>
			<% end %>
		</div>
</div>
<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-Sq6ZBy9oC33y1vxqvw6p42Yw-UUfwws&callback=initMap">
</script>

<script type="text/javascript">
  if ($("#search").val() != "") {
    $('html,body').animate({
      scrollTop: $("#avail-header").offset().top
    });
  }
</script>

app/views/vehicles/new.html.erb
<div class="vehicle_forms">



<h1 id='new-veh-header'>Create New Vehicle</h1>

<%= render 'form' %>

</div>

app/views/vehicles/show.html.erb
<div class="vehicle_show_container">

  <h1 class="owner-title"><%= @vehicle.owner.first_name %>'s Ride</h1>
  <article class="vehicle-details">
    <div class="vehicle-descrip">

      <h2><%= @vehicle.vehicle_year %> <%= @vehicle.vehicle_make %> <%= @vehicle.vehicle_model %></h2>
      <div class="vehicle-image">
        <%= image_tag "#{@vehicle.image}" %>
      </div>
    	<h3><span>Seats</span> <%= @vehicle.seats %></h3>
    	<h3><span>Address</span> <%= @vehicle.street_address %></h3>
    	<h3><span>City</span> <%= @vehicle.city %></h3>
    	<h3><span>Province</span> <%= @vehicle.province %></h3>
    	<h3><span>Postal Code</span> <%= @vehicle.postal_code %></h3>
      <% if current_user != @vehicle.owner %>
        <p class="res-btn"><%= link_to 'Make a Reservation', new_vehicle_reservation_path(@vehicle) %></p>
      <% end %>
      <p class="map-btn">See Car on Map</p>
    </div>
  </article>

  <div class="map-div">
    <div id="map"></div>

  	<script>
  		function initMap() {
  			var map = new google.maps.Map(document.getElementById('map'), {
  				zoom: 16,
          scrollwheel: false,
          mapTypeControl: true,
          mapTypeControlOptions: {
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
          },
          styles: [
            {elementType: 'geometry', stylers: [{color: '#242f3e'}]},
            {elementType: 'labels.text.stroke', stylers: [{color: '#242f3e'}]},
            {elementType: 'labels.text.fill', stylers: [{color: '#746855'}]},
            {
              featureType: 'administrative.locality',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'poi',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'poi.park',
              elementType: 'geometry',
              stylers: [{color: '#263c3f'}]
            },
            {
              featureType: 'poi.park',
              elementType: 'labels.text.fill',
              stylers: [{color: '#6b9a76'}]
            },
            {
              featureType: 'road',
              elementType: 'geometry',
              stylers: [{color: '#38414e'}]
            },
            {
              featureType: 'road',
              elementType: 'geometry.stroke',
              stylers: [{color: '#212a37'}]
            },
            {
              featureType: 'road',
              elementType: 'labels.text.fill',
              stylers: [{color: '#9ca5b3'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'geometry',
              stylers: [{color: '#746855'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'geometry.stroke',
              stylers: [{color: '#1f2835'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'labels.text.fill',
              stylers: [{color: '#f3d19c'}]
            },
            {
              featureType: 'transit',
              elementType: 'geometry',
              stylers: [{color: '#2f3948'}]
            },
            {
              featureType: 'transit.station',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'water',
              elementType: 'geometry',
              stylers: [{color: '#17263c'}]
            },
            {
              featureType: 'water',
              elementType: 'labels.text.fill',
              stylers: [{color: '#515c6d'}]
            },
            {
              featureType: 'water',
              elementType: 'labels.text.stroke',
              stylers: [{color: '#17263c'}]
            }
          ]
  			});

  			var geocoder = new google.maps.Geocoder();
  			var vehicle = "<%= @vehicle.street_address %>, <%= @vehicle.city %>, <%= @vehicle.province %>";

  			geocoder.geocode({'address': vehicle}, function(results, status) {
  				if (status === 'OK') {
  					map.setCenter(results[0].geometry.location);
  					var marker = new google.maps.Marker({
  						map: map,
  						position: results[0].geometry.location
  						});
  				} else {
  					alert('Geocode was not successful for the following reason: ' + status);
  				}
  			});
  		}
  	</script>
  </div>

  <section class="availabilities-container">
    <h3>Availability</h3>
    <div class="availability-container">
      <% weekdays = ["Monday", "Tuesday", "Wednesday","Thursday", "Friday", "Saturday", "Sunday"] %>
      <% weekdays.each do |day| %>
      <% availability = @vehicle.availabilities.find_by(weekday: day) %>
      <div class="weekday-time">
        <li class="availability-weekday">
          <%= day %>
        </li>
        <li id="availability-start">
          <p>
            <%= availability.start_time %>
          </p>
          <p class="availability-p">Availability Start</p>
        </li>
        <li id="availability-end">
          <p>
            <%= availability.end_time %>
          </p>
          <p class="availability-p">Availability End</p>
        </li>
        <% if current_user == @vehicle.owner %>
          <%= link_to "Edit Availability", edit_vehicle_availability_path(@vehicle, availability) %>
        <% end %>
      </div>
      <% end %>

    </div>
  </section>

  <section class="vehicle-reservations">
    <% if current_user == @vehicle.owner %>
      <h2>Your Vehicle's Reservations</h2>
      <% @vehicle.reservations.each do |reservation| %>
      <div class="vehicle-container-reservations">
        <ul>
          <li><span>Date</span> <%= reservation.start_time.strftime("%A %B %d, %Y") %> : <%= reservation.start_time.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %p") %></li>
          <li><span>From</span> <%= reservation.start_location %></li>
          <li><span>To</span> <%= reservation.destination %></li>
        </ul>
      <% end %>
      <p><%= link_to 'Edit Vehicle', edit_vehicle_path(@vehicle) %></p>
      <p><%= link_to 'Delete Vehicle', vehicle_path(@vehicle), method: :delete %></p>
      </div>
    <% end %>
  </section>
</div>


<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-Sq6ZBy9oC33y1vxqvw6p42Yw-UUfwws&callback=initMap">
</script>