config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'users#new'

	 resource :user
	 resources :vehicles do
		 resources :reservations
     resources :availabilities
	 end
	 resource :sessions, only: [:new, :create, :destroy]
end

app/views/layouts/_dropdown_menu.html.erb
<% if current_user %>
  <% if current_user.owned_vehicles.count > 0 %>
    <% id = current_user.owned_vehicles.first.id %>
    <a href="/vehicles/<%= id %>/availabilities">Availability</a>
  <% else %>
    <a href="/vehicles/new">Register a Vehicle</a>
  <% end %>
  <a href="/vehicles">Ride</a>
  <a href="/user">Profile</a>
  <%= link_to "Logout", sessions_path, method: :delete %>
<%else%>
  <a href="/vehicles">Ride</a>
  <a href="/user/new#about-container">About Us</a>
  <a href="/user/new#contact-container">Contact Us</a>
  <!-- <a href="/vehicles/new">Perks</a> -->
<%end%>

app/views/layouts/_head.html.erb
<head>
	<title>Beep</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
  <script src="https://use.fontawesome.com/2fd75991c7.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<%= render partial: '/layouts/head' %>

	<body class="body-container">
		<header class="header">
      <div class="nav-bar">
  			<h1 class="beep-title"><%= link_to 'Beep', new_user_path %></h1>
  			<ul class="nav-links">
  				<div class="dropdown">
  					<i class="fa fa-bars" id="drop-menu-icon" aria-hidden="true"></i>
  					<div class="dropdown-contents">
              <%= render partial: '/layouts/dropdown_menu' %>
            </div>
          </div>
        </ul>
      </div>

      <div class="login-buttons-header">
				<% if current_user %>
					<li class="nav-login nav-login-search">Hello <%= current_user.first_name %> &nbsp; <span class="login-line">|</span> &nbsp; <%= link_to 'Log Out', sessions_path, method: :delete %></li>
				<% else %>
					<li class="nav-login nav-login-search"> <span id="login-nav">  <%= link_to 'Log In', new_user_path %> </span> &nbsp; <span class="login-line">|</span> &nbsp;<span id="signup-nav"> <%= link_to 'Sign Up', new_user_path %> </span> </li>
				<% end %>
      </div>

    </header>


		<!-- <% if flash[:notice]%>
			<p><%=flash[:notice]%></p>
		<% end %> -->
		<%= yield %>
    <footer class="footer">
      <a href="https://www.facebook.com/">
        <i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>
      </a>
      <a href="https://www.instagram.com/">
        <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
      </a>
      <a href="https://www.twitter.com/">
        <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
      </a>
      <p>Beep &copy; 2017</p>
    </footer>
	</body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render partial: '/layouts/head' %>

	<body class="body-container">

    <header class="main-nav-bar">
      <h1 class="beep-title" id="logo-icon"><%= link_to 'Beep', new_user_path %></h1>
      <ul class="nav-links">
        <div class="dropdown">
          <i class="fa fa-bars" id="main-drop-menu-icon" aria-hidden="true"></i>
          <div class="dropdown-contents" id="main-drop-menu">
            <%= render partial: '/layouts/dropdown_menu' %>
          </div>
        </div>
      </ul>
    </header>



		<% if flash[:notice]%>
			<p><%=flash[:notice]%></p>
		<% end %>
		<%= yield %>
    <footer class="homepage-footer footer">
      <a href="https://www.facebook.com/">
        <i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>
      </a>
      <a href="https://www.instagram.com/">
        <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
      </a>
      <a href="https://www.twitter.com/">
        <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
      </a>
      <p>Beep &copy; 2017</p>
    </footer>
  </body>
</html>